### PR TITLE
Scripts to read emails and write SB data

### PR DESCRIPTION
**Pull request by jmedholm**
Reads emails, checks if any previous files exist, and if not cycles through all emails from data@...  and saves it as a CSV. If a CSV exists, it reads it and appends the new data.

### CODE REVIEW

**Comment by jmedholm** [comment]
Actually, line 33 in both files can be ignored. The check just before handles that issue.

**Comment by jmedholm** [comment]
@isgiddy

**Review by isgiddy — CHANGES_REQUESTED** [review]
This looks great Johan. Just wondering if we need that print command? since it will be running on a cronjob I don't think we want any live output?

**Comment by jmedholm** [comment]
Agreed. It was there as a check that the script was working

**Review by jmedholm — COMMENTED** [review]
Removed the print line in both scripts

**Review by isgiddy — APPROVED** [review]

**Pull request merged**
